### Register a user
POST http://localhost:8080/api/user/authorization/register
Content-Type: application/json

{
  "email": "test4@test.com",
  "password": "password"
}

### Login
# @no-cookie-jar
POST http://localhost:8080/api/user/authorization/login
Content-Type: application/json

{
  "email": "test4@test.com",
  "password": "password"
}
